version: "2"         # required to adjust maintainability checks
exclude_patterns:
 - "node_modules/*"
 - "static/js/ckeditor/*"
checks:
  similar-code:
    config:
      threshold: 160
  identical-code:
    config:
      threshold: 55